links:
  parent:
    optional: false
    auto: false
    role: node
    argname: node
  consume:
    - auto: false
      min: 0
      max: 9999
      role: vdisk
      argname: vdisks

recurring:
  - action: monitor
    log: true
    period: 30m
