package ays

import (
	"fmt"

	client "github.com/zero-os/0-orchestrator/api/ays/ays-client"
	"github.com/zero-os/0-orchestrator/api/ays/callback"
)

// Client is the main type of this package, it prove an easy to use API on top of the
// AYS client generated by-goraml
type Client struct {
	// the name of the repos
	repo   string
	client *client.AtYourServiceAPI

	cbMgr *callback.Mgr
}

// NewClient create a new AYS client for a specific AYS repository
// if token is not empty, the Authorization header will be fill with the token and send for each request
func NewClient(url, repo, token string) *Client {
	cl := &Client{
		client: client.NewAtYourServiceAPI(),
	}
	cl.client.AuthHeader = fmt.Sprintf("Bearer %s", token)
	cl.client.BaseURI =url
	return cl
}
