links:
  consume:
    - auto: false
      min: 0
      max: 9999
      role: network
      argname: networks
recurring:
  - action: monitor
    log: true
    period: 30s
longjobs:
    - action: watchdog
