links:
  consume:
    - auto: false
      min: 1
      max: 1
      role: block_cluster
      argname: blockCluster

    - auto: false
      min: 0
      max: 1
      role: object_cluster
      argname: objectCluster

    - auto: false
      min: 0
      max: 1
      role: block_cluster
      argname: slaveCluster
