links:
  consume:
    - auto: false
      min: 1
      max: 1
      role: storage_cluster
      argname: blockCluster

    - auto: false
      min: 1
      max: 1
      role: storage_cluster
      argname: objectCluster

    - auto: false
      min: 1
      max: 1
      role: storage_cluster
      argname: slaveCluster
