package run

//This file is auto-generated by go-raml
//Do not edit this file by hand since it will be overwritten during the next generation

import (
	"net/http"

	"github.com/gorilla/mux"
	"github.com/justinas/alice"
	"github.com/zero-os/0-orchestrator/api/tools"
)

// RunsInterface is interface for /runs root endpoint
type RunsInterface interface { // GetRunState is the handler for GET /runs
	// Get Run Status
	GetRunState(http.ResponseWriter, *http.Request)
	// Wait on run
	WaitOnRun(http.ResponseWriter, *http.Request)
}

// RunsInterfaceRoutes is routing for /runs root endpoint
func RunsInterfaceRoutes(r *mux.Router, i RunsInterface, org string) {
	r.Handle("/runs/{runid}", alice.New(tools.NewOauth2itsyouonlineMiddleware(org).Handler).Then(http.HandlerFunc(i.GetRunState))).Methods("GET")
	r.Handle("/runs/{runid}/wait", alice.New(tools.NewOauth2itsyouonlineMiddleware(org).Handler).Then(http.HandlerFunc(i.WaitOnRun))).Methods("GET")
}
