links:
  parent:
    auto: false
    role: storagepool
    optional: false
    argname: storagePool

recurring:
  - action: update_sizeOnDisk
    log: true
    period: 30m
  - action: monitor
    log: true
    period: 15m
