package vdisk

//This file is auto-generated by go-raml
//Do not edit this file by hand since it will be overwritten during the next generation

import (
	"net/http"

	"github.com/gorilla/mux"
	"github.com/justinas/alice"
	"github.com/zero-os/0-orchestrator/api/tools"
)

// VdisksInterface is interface for /vdisks root endpoint
type VdisksInterface interface { // ResizeVdisk is the handler for POST /vdisks/{vdiskid}/resize
	// Resize vdisk
	ResizeVdisk(http.ResponseWriter, *http.Request)
	// RollbackVdisk is the handler for POST /vdisks/{vdiskid}/rollback
	// Rollback a vdisk to a previous state
	RollbackVdisk(http.ResponseWriter, *http.Request)
	// DeleteVdisk is the handler for DELETE /vdisks/{vdiskid}
	// Delete Vdisk
	DeleteVdisk(http.ResponseWriter, *http.Request)
	// GetVdiskInfo is the handler for GET /vdisks/{vdiskid}
	// Get vdisk information
	GetVdiskInfo(http.ResponseWriter, *http.Request)
	// ListVdisks is the handler for GET /vdisks
	// List vdisks
	ListVdisks(http.ResponseWriter, *http.Request)
	// CreateNewVdisk is the handler for POST /vdisks
	// Create a new vdisk, can be a copy from an existing vdisk
	CreateNewVdisk(http.ResponseWriter, *http.Request)
}

// VdisksInterfaceRoutes is routing for /vdisks root endpoint
func VdisksInterfaceRoutes(r *mux.Router, i VdisksInterface, org string) {
	r.Handle("/vdisks/{vdiskid}/resize", alice.New(tools.NewOauth2itsyouonlineMiddleware(org).Handler).Then(http.HandlerFunc(i.ResizeVdisk))).Methods("POST")
	r.Handle("/vdisks/{vdiskid}/rollback", alice.New(tools.NewOauth2itsyouonlineMiddleware(org).Handler).Then(http.HandlerFunc(i.RollbackVdisk))).Methods("POST")
	r.Handle("/vdisks/{vdiskid}", alice.New(tools.NewOauth2itsyouonlineMiddleware(org).Handler).Then(http.HandlerFunc(i.DeleteVdisk))).Methods("DELETE")
	r.Handle("/vdisks/{vdiskid}", alice.New(tools.NewOauth2itsyouonlineMiddleware(org).Handler).Then(http.HandlerFunc(i.GetVdiskInfo))).Methods("GET")
	r.Handle("/vdisks", alice.New(tools.NewOauth2itsyouonlineMiddleware(org).Handler).Then(http.HandlerFunc(i.ListVdisks))).Methods("GET")
	r.Handle("/vdisks", alice.New(tools.NewOauth2itsyouonlineMiddleware(org).Handler).Then(http.HandlerFunc(i.CreateNewVdisk))).Methods("POST")
}
