package storagecluster

//This file is auto-generated by go-raml
//Do not edit this file by hand since it will be overwritten during the next generation

import (
	"net/http"

	"github.com/gorilla/mux"
	"github.com/justinas/alice"
	"github.com/zero-os/0-orchestrator/api/tools"
)

// StorageclustersInterface is interface for /storageclusters root endpoint
type StorageclustersInterface interface { // KillCluster is the handler for DELETE /storageclusters/{label}
	// Kill cluster
	KillCluster(http.ResponseWriter, *http.Request)
	// GetClusterInfo is the handler for GET /storageclusters/{label}
	// Get full information about specific cluster
	GetClusterInfo(http.ResponseWriter, *http.Request)
	// ListAllClusters is the handler for GET /storageclusters
	// List all running clusters
	ListAllClusters(http.ResponseWriter, *http.Request)
	// DeployNewCluster is the handler for POST /storageclusters
	// Deploy new cluster
	DeployNewCluster(http.ResponseWriter, *http.Request)
}

// StorageclustersInterfaceRoutes is routing for /storageclusters root endpoint
func StorageclustersInterfaceRoutes(r *mux.Router, i StorageclustersInterface, org string) {
	r.Handle("/storageclusters/{label}", alice.New(tools.NewOauth2itsyouonlineMiddleware(org).Handler).Then(http.HandlerFunc(i.KillCluster))).Methods("DELETE")
	r.Handle("/storageclusters/{label}", alice.New(tools.NewOauth2itsyouonlineMiddleware(org).Handler).Then(http.HandlerFunc(i.GetClusterInfo))).Methods("GET")
	r.Handle("/storageclusters", alice.New(tools.NewOauth2itsyouonlineMiddleware(org).Handler).Then(http.HandlerFunc(i.ListAllClusters))).Methods("GET")
	r.Handle("/storageclusters", alice.New(tools.NewOauth2itsyouonlineMiddleware(org).Handler).Then(http.HandlerFunc(i.DeployNewCluster))).Methods("POST")
}
