links:
  consume:
    - role: storage_cluster
      argname: storageCluster
      auto: false
      min: 1
      max: 1

    - role: storage_cluster
      argname: tlogStoragecluster
      auto: false
      min: 1
      max: 1
