links:
  consume:
    - role: storage_cluster
      argname: blockStoragecluster
      auto: false
      min: 1
      max: 1

    - role: storage_cluster
      argname: backupStoragecluster
      auto: false
      min: 0
      max: 1

    - role: storage_cluster
      argname: objectStoragecluster
      auto: false
      min: 0
      max: 1
