links:
  parent:
    role: container
    argname: container
    auto: false
    optional: false
  consume:
    - auto: false
      min: 0
      max: 1
      role: tlogserver
      argname: tlogserver

recurring:
  - action: monitor
    log: true
    period: 1m
