package graph

//This file is auto-generated by go-raml
//Do not edit this file by hand since it will be overwritten during the next generation

import (
	"net/http"

	"github.com/gorilla/mux"
)

// GraphsInterface is interface for /graphs root endpoint
type GraphsInterface interface { // DeleteDashboard is the handler for DELETE /graphs/{graphid}/dashboards/{dashboardname}
	// Delete dashboard
	DeleteDashboard(http.ResponseWriter, *http.Request)
	// GetDashboard is the handler for GET /graphs/{graphid}/dashboards/{dashboardname}
	// Get dashboard
	GetDashboard(http.ResponseWriter, *http.Request)
	// CreateDashboard is the handler for POST /graphs/{graphid}/dashboards
	// Create dashboard
	CreateDashboard(http.ResponseWriter, *http.Request)
	// ListDashboards is the handler for GET /graphs/{graphid}/dashboards
	// List all dashboards
	ListDashboards(http.ResponseWriter, *http.Request)
	// GetGraph is the handler for GET /graphs/{graphid}
	// Get a graph
	GetGraph(http.ResponseWriter, *http.Request)
	// ListGraphs is the handler for GET /graphs
	// List all graphs
	ListGraphs(http.ResponseWriter, *http.Request)
	// UpdateGraph is the handler for PUT /graphs/{graphid}
	// Update graph
	UpdateGraph(http.ResponseWriter, *http.Request)
}

// GraphsInterfaceRoutes is routing for /graphs root endpoint
func GraphsInterfaceRoutes(r *mux.Router, i GraphsInterface, org string) {
	r.HandleFunc("/graphs/{graphid}/dashboards/{dashboardname}", i.DeleteDashboard).Methods("DELETE")
	r.HandleFunc("/graphs/{graphid}/dashboards/{dashboardname}", i.GetDashboard).Methods("GET")
	r.HandleFunc("/graphs/{graphid}/dashboards", i.CreateDashboard).Methods("POST")
	r.HandleFunc("/graphs/{graphid}/dashboards", i.ListDashboards).Methods("GET")
	r.HandleFunc("/graphs/{graphid}", i.GetGraph).Methods("GET")
	r.HandleFunc("/graphs/{graphid}", i.UpdateGraph).Methods("PUT")
	r.HandleFunc("/graphs", i.ListGraphs).Methods("GET")
}
