package vdiskstorage

//This file is auto-generated by go-raml
//Do not edit this file by hand since it will be overwritten during the next generation

import (
	"net/http"

	"github.com/gorilla/mux"
)

// VdiskstorageInterface is interface for /vdiskstorage root endpoint
type VdiskstorageInterface interface { // GetVdiskStorageInfo is the handler for GET /vdiskstorage/{vdiskstorageid}
	// Get vdisk storage information
	GetVdiskStorageInfo(http.ResponseWriter, *http.Request)
	// ListVdiskStorages is the handler for GET /vdiskstorage
	// List vdisks storages
	ListVdiskStorages(http.ResponseWriter, *http.Request)
	// CreateNewVdiskStorage is the handler for POST /vdiskstorage
	// Create a new vdisk storage, can be a copy from an existing vdisk
	CreateNewVdiskStorage(http.ResponseWriter, *http.Request)
}

// VdiskstorageInterfaceRoutes is routing for /vdiskstorage root endpoint
func VdiskstorageInterfaceRoutes(r *mux.Router, i VdiskstorageInterface, org string) {
	r.HandleFunc("/vdiskstorage/{vdiskstorageid}", i.GetVdiskStorageInfo).Methods("GET")
	r.HandleFunc("/vdiskstorage", i.ListVdiskStorages).Methods("GET")
	r.HandleFunc("/vdiskstorage", i.CreateNewVdiskStorage).Methods("POST")
}
