package backup

//This file is auto-generated by go-raml
//Do not edit this file by hand since it will be overwritten during the next generation

import (
	"net/http"

	"github.com/gorilla/mux"
)

// StorageclustersInterface is interface for /storageclusters root endpoint
type BackupInterface interface { // KillCluster is the handler for DELETE /storageclusters/{label}
	// Create a backup
	Create(http.ResponseWriter, *http.Request)
	// List backups
	List(http.ResponseWriter, *http.Request)
}

// StorageclustersInterfaceRoutes is routing for /storageclusters root endpoint
func BackupInterfaceRoutes(r *mux.Router, i BackupInterface, org string) {
	r.HandleFunc("/backup", i.Create).Methods("POST")
	r.HandleFunc("/backup", i.List).Methods("GET")
}
